const quotesDB = [
    { quote: "Success is not final; failure is not fatal: It is the courage to continue that counts.", author: "Winston S. Churchill" },
    { quote: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
    { quote: "Don't watch the clock; do what it does. Keep going.", author: "Sam Levenson" },
    { quote: "Opportunities don't happen, you create them.", author: "Chris Grosser" },
    { quote: "Your time is limited, so don't waste it living someone else's life.", author: "Steve Jobs" },
    { quote: "Hard work beats talent when talent doesn’t work hard.", author: "Tim Notke" },
    { quote: "Success usually comes to those who are too busy to be looking for it.", author: "Henry David Thoreau" },
    { quote: "Don't be afraid to give up the good to go for the great.", author: "John D. Rockefeller" },
    { quote: "I find that the harder I work, the more luck I seem to have.", author: "Thomas Jefferson" },
    { quote: "Success is not the key to happiness. Happiness is the key to success.", author: "Albert Schweitzer" },
    { quote: "The only limit to our realization of tomorrow is our doubts of today.", author: "Franklin D. Roosevelt" },
    { quote: "Do not wait to strike till the iron is hot; but make it hot by striking.", author: "William Butler Yeats" },
    { quote: "It always seems impossible until it’s done.", author: "Nelson Mandela" },
    { quote: "Don’t let yesterday take up too much of today.", author: "Will Rogers" },
    { quote: "If you are not willing to risk the usual, you will have to settle for the ordinary.", author: "Jim Rohn" },
    { quote: "Whether you think you can or you think you can't, you're right.", author: "Henry Ford" },
    { quote: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
    { quote: "The best time to plant a tree was 20 years ago. The second best time is now.", author: "Chinese Proverb" },
    { quote: "If you're going through hell, keep going.", author: "Winston S. Churchill" },
    { quote: "I never dreamed about success, I worked for it.", author: "Estee Lauder" },
    { quote: "Don't limit your challenges. Challenge your limits.", author: "Unknown" },
    { quote: "The harder the battle, the sweeter the victory.", author: "Les Brown" },
    { quote: "Dream big and dare to fail.", author: "Norman Vaughan" },
    { quote: "The way to get started is to quit talking and begin doing.", author: "Walt Disney" },
    { quote: "Failure will never overtake me if my determination to succeed is strong enough.", author: "Og Mandino" },
    // Additional 100 quotes start here
    { quote: "The only place where success comes before work is in the dictionary.", author: "Vidal Sassoon" },
    { quote: "Act as if what you do makes a difference. It does.", author: "William James" },
    { quote: "Success is walking from failure to failure with no loss of enthusiasm.", author: "Winston S. Churchill" },
    { quote: "The road to success and the road to failure are almost exactly the same.", author: "Colin R. Davis" },
    { quote: "Don’t let the fear of losing be greater than the excitement of winning.", author: "Robert Kiyosaki" },
    { quote: "You miss 100% of the shots you don’t take.", author: "Wayne Gretzky" },
    { quote: "You only live once, but if you do it right, once is enough.", author: "Mae West" },
    { quote: "The way to achieve your own success is to be willing to help somebody else get it first.", author: "Iyanla Vanzant" },
    { quote: "Try not to become a person of success, but rather try to become a person of value.", author: "Albert Einstein" },
    { quote: "You can do anything, but not everything.", author: "David Allen" },
    { quote: "Success is how high you bounce when you hit bottom.", author: "George S. Patton" },
    { quote: "The only limit to our realization of tomorrow is our doubts of today.", author: "Franklin D. Roosevelt" },
    { quote: "Don’t be afraid to give up the good to go for the great.", author: "John D. Rockefeller" },
    { quote: "I attribute my success to this: I never gave or took any excuse.", author: "Florence Nightingale" },
    { quote: "The question isn’t who is going to let me; it’s who is going to stop me.", author: "Ayn Rand" },
    { quote: "It does not matter how slowly you go, so long as you do not stop.", author: "Confucius" },
    { quote: "Do what you can, with what you have, where you are.", author: "Theodore Roosevelt" },
    { quote: "The best revenge is massive success.", author: "Frank Sinatra" },
    { quote: "Don’t wait for the right opportunity: create it.", author: "George Bernard Shaw" },
    { quote: "In the middle of every difficulty lies opportunity.", author: "Albert Einstein" },
    { quote: "Success is not the absence of failure; it's the persistence through failure.", author: "Aisha Tyler" },
    { quote: "Action is the foundational key to all success.", author: "Pablo Picasso" },
    { quote: "The successful warrior is the average man, with laser-like focus.", author: "Bruce Lee" },
    { quote: "Success is not in what you have, but who you are.", author: "Bo Bennett" },
    { quote: "Don’t let what you cannot do interfere with what you can do.", author: "John Wooden" },
    { quote: "Success is dependent on effort.", author: "Sophocles" },
    { quote: "Believe in yourself and all that you are.", author: "Christian D. Larson" },
    { quote: "Success is never accidental.", author: "Jack Dorsey" },
    { quote: "You must expect great things of yourself before you can do them.", author: "Michael Jordan" },
    { quote: "The only thing that stands between you and success is the will to try and the belief that it is possible.", author: "Joel Brown" },
    { quote: "What seems to us as bitter trials are often blessings in disguise.", author: "Oscar Wilde" },
    { quote: "Success is a journey, not a destination.", author: "Arthur Ashe" },
    { quote: "If you cannot do great things, do small things in a great way.", author: "Napoleon Hill" },
    { quote: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe" },
    { quote: "Success is getting what you want, happiness is wanting what you get.", author: "W. P. Kinsella" },
    { quote: "Great things never came from comfort zones.", author: "Neil Strauss" },
    { quote: "Success is 1% inspiration and 99% perspiration.", author: "Thomas Edison" },
    { quote: "Success is not about being the best. It’s about always getting better.", author: "Behdad Sami" },
    { quote: "The harder I work, the luckier I get.", author: "Gary Player" },
    { quote: "A champion is someone who gets up when they can’t.", author: "Jack Dempsey" },
    { quote: "Success is simple. Do what's right, the right way, at the right time.", author: "Arnold H. Glasow" },
    { quote: "Success is liking yourself, liking what you do, and liking how you do it.", author: "Maya Angelou" },
    { quote: "The only real mistake is the one from which we learn nothing.", author: "Henry Ford" },
    { quote: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis" },
    { quote: "Success is stumbling from failure to failure with no loss of enthusiasm.", author: "Winston S. Churchill" },
    { quote: "To succeed in life, you need two things: ignorance and confidence.", author: "Mark Twain" },
    { quote: "Success is not how high you have climbed, but how you make a positive difference to the world.", author: "Roy T. Bennett" },
    { quote: "Don’t let yesterday take up too much of today.", author: "Will Rogers" },
    { quote: "Don't be afraid to start over. This time you’re not starting from scratch, you’re starting from experience.", author: "Unknown" },
    { quote: "Success is best when it's shared.", author: "Howard Schultz" },
    { quote: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
    { quote: "Nothing in the world can take the place of persistence.", author: "Calvin Coolidge" },
    { quote: "Success doesn’t come to you, you go to it.", author: "Marva Collins" },
    { quote: "The road to success is always under construction.", author: "Lily Tomlin" },
    { quote: "Success is about creating value, not just making money.", author: "Oprah Winfrey" },
    { quote: "Dream it. Wish it. Do it.", author: "Unknown" },
    { quote: "Success is 20% skills and 80% strategy.", author: "Jim Rohn" },
    { quote: "The best revenge is massive success.", author: "Frank Sinatra" },
    { quote: "You can’t build a reputation on what you are going to do.", author: "Henry Ford" },
    { quote: "Success doesn’t come from what you do occasionally, it comes from what you do consistently.", author: "Marie Forleo" },
    { quote: "Success usually comes to those who are too busy to be looking for it.", author: "Henry David Thoreau" }  
  ];
  
  export default quotesDB;
  